remy:
  target: "{{ env_var('DBT_TARGET', 'nonprod') }}"
  outputs:
    nonprod:
      type: duckdb
      path: "{{ env_var('DBT_NONPROD_PATH', 'target/nonprod.duckdb') }}"
      schema: main
      threads: 1
      extensions:
        - parquet
        - ducklake
      attach:
        - path: "ducklake:sqlite:target/nonprod/ducklake/catalog.sqlite"
          alias: lake
          options:
            data_path: "target/nonprod/ducklake/data"
    prod:
      type: duckdb
      path: "{{ env_var('DBT_PROD_PATH', 'target/prod.duckdb') }}"
      schema: main
      threads: 1
      extensions:
        - parquet
        - ducklake
      attach:
        - path: "ducklake:sqlite:target/prod/ducklake/catalog.sqlite"
          alias: lake
          options:
            data_path: "target/prod/ducklake/data"
